[#96] Fix script execution
kbss-cvut/s-pipes-editor-ui pull request #109
Opened 2024-12-30 23:50 UTC by palagdan

2025-01-06 23:00 UTC, blcham requested changes
see my comments (maybe discussion is needed)

2025-01-09 11:36 UTC, palagdan commented on deploy/docker-compose.yml
> +  #      - /usr/local/tomcat/temp/:/usr/local/tomcat/temp/
@blcham 
I use Linux and encountered an issue with mounting the path /usr/local/tomcat/temp/. Every time I wanted to run docker-compose, I had to manually comment out ` #      - /usr/local/tomcat/temp/:/usr/local/tomcat/temp/` . After investigating the problem, I discovered that my Docker installation was done via Snap, which caused this issue.

It might be a good idea to add a warning about this to the README. Here's a related discussion: https://stackoverflow.com/questions/45764477/docker-compose-error-while-creating-mount-source-path.

2025-02-03 14:48 UTC, blcham commented
@cipmo

2025-02-05 13:52 UTC, blcham commented on deploy/docker-compose.yml
> +  #      - /usr/local/tomcat/temp/:/usr/local/tomcat/temp/
This should be solved in https://github.com/kbss-cvut/s-pipes-editor-ui/issues/116

2025-02-05 13:52 UTC, merged